### PR TITLE
minor change to curl command

### PR DESCRIPTION
**Pull request by parkerduckworth**
I temporarily made a repo called 'halyard' and tested out the install command from the README. I made a minor tweak to the command, and the install script now works as expected:

1. clone the repo to the users home directory
2. copies the main script to /usr/local/bin and gives it executable permission
3. Locks the Dockerfile and builds the docker image in the "container" directory

Everything works well once the install is complete.

Noted, this will only work if the projects is located at github.com/parkerduckworth/halyard , rather than halyard-dev

Also, rather than continuing to commit to master like a heathen, I will from now on push changes through new branches.

Setting up CI wouldn't be a bad idea either, once all the code has been cleaned to meet the Google Shell style guide (BTW, I didn't decide to conform to this until after the code was written, and it was an arbitrary choice. If you have a better idea, let me know)

### CODE REVIEW

**Comment by parkerduckworth** [comment]
On the change from "bash" -> "/bin/bash", it seems to be more portable.  Also, that's the format [Homebrew uses](https://github.com/Homebrew/install) (from whom I lifted this curl expression)

**Comment by parkerduckworth** [comment]
@ericdeansanchez

**Review by ericdeansanchez — COMMENTED** [review]
What is the benefit of using ```-c``` over ```-e```?

**Comment by parkerduckworth** [comment]
The `-e` was left over from the ruby expression used by Homebrew install. I should have changed it when changing the interpreter to bash.

In ruby, `-e` does the same thing as bash's `-c` : interprets the string as a command.
In bash, `-e` (in this context) catches nonzero exit status and terminates the process

**Pull request merged**
